### ISSUE TITLE
Screenshot fails: Error: EXDEV: cross-device link not permitted, rename ...

### ISSUE THREAD

**Issue by htho** [bsmithb2/testcafe-browser-provider-android#9]
Screenshots can not be taken if the target directory is in another filesystem than the cwd.
```
Was unable to take a screenshot due to an error.

Error: EXDEV: cross-device link not permitted, rename 'screen.png' -> '/home/testsystem/network/share/test/android_chrome/master/0_Start.png'
    at renameSync (fs.js:598:3)
    at BrowserProviderPluginHost._callee6$ (/home/testsystem/TestSuite/node_modules/testcafe-browser-provider-android/lib/index.js:581:48)
    at tryCatch (/home/testsystem/TestSuite/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/testsystem/TestSuite/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/testsystem/TestSuite/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/testsystem/TestSuite/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/testsystem/TestSuite/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```
This can be resolved by switching from rename to copy&unlink
https://stackoverflow.com/questions/37153666/error-exdev-cross-device-link-not-permitted-rename-tmp-on-ubuntu-16-04-lts#44146825

**Comment by htho** [comment]
resolved by #10
